name = "TensorNetworkCodes"
uuid = "b317c587-d840-4e81-9857-9d906192e215"
authors = ["Terry Farrelly", "David K. Tuckett"]
version = "0.1.0"

[deps]
Qecsim = "e6c2bad3-a74c-45bb-aaa0-aff4e9ffa0d7"

[compat]
julia = "1"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets"]
